public  class Cat {
    public  string name;
    public string color ;
    // parameterized consturctor
        //similar to method.
        //But does NOT return 
        
    public Cat(string n,string clr ){
        name=n;
        color=clr;
        sleeping();

    }
    // name is same as class name 
    // does not return anything 
    // this is non- parameterized constructor
    public void sleeping(){
        
    }
}