public class Player {
    public static void playing(){
        String player1Name='Ronaldo';
        system.debug(player1Name);
        String player2Name='Messi';
        system.debug(player2Name);
        String player3Name='Ahmet';
        system.debug(player3Name);
        String player4Name='Q7';
        system.debug(player4Name);
        String player5Name='Rustu';
        system.debug(player5Name);
    }
}
