Map<String,String> zipCodeMap=new Map<String,String>();
zipCodeMap.put('380061', 'Ahmedbad');
zipCodeMap.put('110001', 'Goa');
zipCodeMap.put('110001', 'Delhi');
zipCodeMap.put('110001', 'New Delhi');
zipCodeMap.put('90001', 'California');
zipCodeMap.put('96501', 'California');
system.debug(zipCodeMap);


Map<integer,string> m2=new Map<integer,string>();
m2.put(1, 'one');
m2.put(2, 'five');
m2.put(3, 'nine');
system.debug(m2);

